---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destinations:
    - namespace: "argo"
      server: "*"
  sourceRepos:
    - "*"
  sourceNamespaces:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
