---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  description: Project for Infra apps
  sourceNamespaces:
    - "*"
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
