---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destinations:
    - namespace: "argo"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
  sourceNamespaces:
    - "argo"
