apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
  namespace: kube-argocd
spec:
  destination:
    namespace: example
    server: https://kubernetes.default.svc
  project: test
  source:
    path: charts/example
    repoURL: https://git.exness.io/nikita.lipchik/helm-example.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
